import Head from "next/head";

import Header from "./Components/Header";
import Hero from "./Components/Hero";
import Footer from "./Components/Footer";

import { Container } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Container
        maxW="container.xl"
        h="calc(100vh - 7rem)"
        display="flex"
        flexDirection="column"
        alignItems="center"
        justifyContent="center"
      >
        <Hero />
      </Container>

      <Footer />
    </>
  );
}
